Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,6 +33,23 @@ jobs:
           AWS_REGION: 'us-east-1'
         run: |
           sam deploy --no-confirm-changeset --stack-name crypto-app --capabilities CAPABILITY_IAM --region $AWS_REGION --resolve-s3
+        continue-on-error: true
+
+      - name: Check Deployment Status
+        if: failure()
+        run: |
+          DEPLOY_EXIT_CODE=$(cat $GITHUB_WORKSPACE/DEPLOY_EXIT_CODE)
+          if [ "$DEPLOY_EXIT_CODE" -eq 0 ]; then
+            echo "Deployment was successful."
+          elif [ "$DEPLOY_EXIT_CODE" -eq 1 ]; then
+            echo "No changes to deploy. Stack is up to date."
+            exit 0
+          else
+            echo "Deployment failed with exit code $DEPLOY_EXIT_CODE."
+            exit 1
+          fi
+        env:
+          GITHUB_WORKSPACE: ${{ github.workspace }}
 
       - name: Configure Git
         run: |
